<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Flight;

class FlightSeeder extends Seeder
{
    public function run(): void
    {
        $flights = [
            // ========== KATHMANDU → POKHARA ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 101',
                'from_city' => 'Kathmandu',
                'to_city' => 'Pokhara',
                'departure_time' => '07:00:00',
                'arrival_time' => '07:25:00',
                'duration' => '25 min',
                'fare' => 9500,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 42,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 201',
                'from_city' => 'Kathmandu',
                'to_city' => 'Pokhara',
                'departure_time' => '12:30:00',
                'arrival_time' => '12:55:00',
                'duration' => '25 min',
                'fare' => 8900,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 28,
            ],
            [
                'airline' => 'Shree Airlines',
                'flight_number' => 'SHA 305',
                'from_city' => 'Kathmandu',
                'to_city' => 'Pokhara',
                'departure_time' => '16:45:00',
                'arrival_time' => '17:10:00',
                'duration' => '25 min',
                'fare' => 10500,
                'refundable' => true,
                'aircraft' => 'Bombardier CRJ-200',
                'baggage' => '25 kg checked + 7 kg hand',
                'seats_available' => 35,
            ],

            // ========== KATHMANDU → BIRATNAGAR ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 501',
                'from_city' => 'Kathmandu',
                'to_city' => 'Biratnagar',
                'departure_time' => '08:15:00',
                'arrival_time' => '09:05:00',
                'duration' => '50 min',
                'fare' => 12500,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 38,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 401',
                'from_city' => 'Kathmandu',
                'to_city' => 'Biratnagar',
                'departure_time' => '13:20:00',
                'arrival_time' => '14:10:00',
                'duration' => '50 min',
                'fare' => 11200,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 22,
            ],
            [
                'airline' => 'Nepal Airlines',
                'flight_number' => 'RA 205',
                'from_city' => 'Kathmandu',
                'to_city' => 'Biratnagar',
                'departure_time' => '18:00:00',
                'arrival_time' => '18:50:00',
                'duration' => '50 min',
                'fare' => 13500,
                'refundable' => true,
                'aircraft' => 'Boeing 737-800',
                'baggage' => '30 kg checked + 7 kg hand',
                'seats_available' => 55,
            ],

            // ========== KATHMANDU → BHAIRAHAWA ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 601',
                'from_city' => 'Kathmandu',
                'to_city' => 'Bhairahawa',
                'departure_time' => '09:30:00',
                'arrival_time' => '10:15:00',
                'duration' => '45 min',
                'fare' => 11800,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 40,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 601',
                'from_city' => 'Kathmandu',
                'to_city' => 'Bhairahawa',
                'departure_time' => '14:45:00',
                'arrival_time' => '15:30:00',
                'duration' => '45 min',
                'fare' => 10500,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 18,
            ],
            [
                'airline' => 'Shree Airlines',
                'flight_number' => 'SHA 701',
                'from_city' => 'Kathmandu',
                'to_city' => 'Bhairahawa',
                'departure_time' => '19:15:00',
                'arrival_time' => '20:00:00',
                'duration' => '45 min',
                'fare' => 12800,
                'refundable' => true,
                'aircraft' => 'Bombardier CRJ-200',
                'baggage' => '25 kg checked + 7 kg hand',
                'seats_available' => 30,
            ],

            // ========== KATHMANDU → NEPALGUNJ ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 801',
                'from_city' => 'Kathmandu',
                'to_city' => 'Nepalgunj',
                'departure_time' => '10:00:00',
                'arrival_time' => '11:00:00',
                'duration' => '1h 00min',
                'fare' => 14500,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 45,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 801',
                'from_city' => 'Kathmandu',
                'to_city' => 'Nepalgunj',
                'departure_time' => '15:30:00',
                'arrival_time' => '16:30:00',
                'duration' => '1h 00min',
                'fare' => 13200,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 20,
            ],
            [
                'airline' => 'Nepal Airlines',
                'flight_number' => 'RA 801',
                'from_city' => 'Kathmandu',
                'to_city' => 'Nepalgunj',
                'departure_time' => '20:00:00',
                'arrival_time' => '21:00:00',
                'duration' => '1h 00min',
                'fare' => 16000,
                'refundable' => true,
                'aircraft' => 'Boeing 737-800',
                'baggage' => '30 kg checked + 7 kg hand',
                'seats_available' => 60,
            ],

            // ========== KATHMANDU → JANAKPUR ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 901',
                'from_city' => 'Kathmandu',
                'to_city' => 'Janakpur',
                'departure_time' => '07:45:00',
                'arrival_time' => '08:20:00',
                'duration' => '35 min',
                'fare' => 9800,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 40,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 901',
                'from_city' => 'Kathmandu',
                'to_city' => 'Janakpur',
                'departure_time' => '12:00:00',
                'arrival_time' => '12:35:00',
                'duration' => '35 min',
                'fare' => 8900,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 25,
            ],
            [
                'airline' => 'Shree Airlines',
                'flight_number' => 'SHA 901',
                'from_city' => 'Kathmandu',
                'to_city' => 'Janakpur',
                'departure_time' => '17:30:00',
                'arrival_time' => '18:05:00',
                'duration' => '35 min',
                'fare' => 11500,
                'refundable' => true,
                'aircraft' => 'Bombardier CRJ-200',
                'baggage' => '25 kg checked + 7 kg hand',
                'seats_available' => 32,
            ],
        ];

        foreach ($flights as $flight) {
            Flight::create($flight);
        }
    }
}