<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Flight;

class ReturnFlightSeeder extends Seeder
{
    public function run(): void
    {
        $flights = [
            // ========== POKHARA → KATHMANDU ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 102',
                'from_city' => 'Pokhara',
                'to_city' => 'Kathmandu',
                'departure_time' => '08:15:00',
                'arrival_time' => '08:40:00',
                'duration' => '25 min',
                'fare' => 9500,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 42,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 202',
                'from_city' => 'Pokhara',
                'to_city' => 'Kathmandu',
                'departure_time' => '14:00:00',
                'arrival_time' => '14:25:00',
                'duration' => '25 min',
                'fare' => 8900,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 28,
            ],
            [
                'airline' => 'Shree Airlines',
                'flight_number' => 'SHA 306',
                'from_city' => 'Pokhara',
                'to_city' => 'Kathmandu',
                'departure_time' => '18:30:00',
                'arrival_time' => '18:55:00',
                'duration' => '25 min',
                'fare' => 10500,
                'refundable' => true,
                'aircraft' => 'Bombardier CRJ-200',
                'baggage' => '25 kg checked + 7 kg hand',
                'seats_available' => 35,
            ],

            // ========== BIRATNAGAR → KATHMANDU ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 502',
                'from_city' => 'Biratnagar',
                'to_city' => 'Kathmandu',
                'departure_time' => '09:45:00',
                'arrival_time' => '10:35:00',
                'duration' => '50 min',
                'fare' => 12500,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 38,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 402',
                'from_city' => 'Biratnagar',
                'to_city' => 'Kathmandu',
                'departure_time' => '15:00:00',
                'arrival_time' => '15:50:00',
                'duration' => '50 min',
                'fare' => 11200,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 22,
            ],
            [
                'airline' => 'Nepal Airlines',
                'flight_number' => 'RA 206',
                'from_city' => 'Biratnagar',
                'to_city' => 'Kathmandu',
                'departure_time' => '19:30:00',
                'arrival_time' => '20:20:00',
                'duration' => '50 min',
                'fare' => 13500,
                'refundable' => true,
                'aircraft' => 'Boeing 737-800',
                'baggage' => '30 kg checked + 7 kg hand',
                'seats_available' => 55,
            ],

            // ========== BHAIRAHAWA → KATHMANDU ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 602',
                'from_city' => 'Bhairahawa',
                'to_city' => 'Kathmandu',
                'departure_time' => '10:45:00',
                'arrival_time' => '11:30:00',
                'duration' => '45 min',
                'fare' => 11800,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 40,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 602',
                'from_city' => 'Bhairahawa',
                'to_city' => 'Kathmandu',
                'departure_time' => '16:00:00',
                'arrival_time' => '16:45:00',
                'duration' => '45 min',
                'fare' => 10500,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 18,
            ],
            [
                'airline' => 'Shree Airlines',
                'flight_number' => 'SHA 702',
                'from_city' => 'Bhairahawa',
                'to_city' => 'Kathmandu',
                'departure_time' => '20:30:00',
                'arrival_time' => '21:15:00',
                'duration' => '45 min',
                'fare' => 12800,
                'refundable' => true,
                'aircraft' => 'Bombardier CRJ-200',
                'baggage' => '25 kg checked + 7 kg hand',
                'seats_available' => 30,
            ],

            // ========== NEPALGUNJ → KATHMANDU ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 802',
                'from_city' => 'Nepalgunj',
                'to_city' => 'Kathmandu',
                'departure_time' => '11:30:00',
                'arrival_time' => '12:30:00',
                'duration' => '1h 00min',
                'fare' => 14500,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 45,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 802',
                'from_city' => 'Nepalgunj',
                'to_city' => 'Kathmandu',
                'departure_time' => '17:00:00',
                'arrival_time' => '18:00:00',
                'duration' => '1h 00min',
                'fare' => 13200,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 20,
            ],
            [
                'airline' => 'Nepal Airlines',
                'flight_number' => 'RA 802',
                'from_city' => 'Nepalgunj',
                'to_city' => 'Kathmandu',
                'departure_time' => '21:15:00',
                'arrival_time' => '22:15:00',
                'duration' => '1h 00min',
                'fare' => 16000,
                'refundable' => true,
                'aircraft' => 'Boeing 737-800',
                'baggage' => '30 kg checked + 7 kg hand',
                'seats_available' => 60,
            ],

            // ========== JANAKPUR → KATHMANDU ==========
            [
                'airline' => 'Buddha Air',
                'flight_number' => 'U4 902',
                'from_city' => 'Janakpur',
                'to_city' => 'Kathmandu',
                'departure_time' => '09:00:00',
                'arrival_time' => '09:35:00',
                'duration' => '35 min',
                'fare' => 9800,
                'refundable' => true,
                'aircraft' => 'ATR 72-500',
                'baggage' => '20 kg checked + 5 kg hand',
                'seats_available' => 40,
            ],
            [
                'airline' => 'Yeti Airlines',
                'flight_number' => 'YT 902',
                'from_city' => 'Janakpur',
                'to_city' => 'Kathmandu',
                'departure_time' => '13:30:00',
                'arrival_time' => '14:05:00',
                'duration' => '35 min',
                'fare' => 8900,
                'refundable' => false,
                'aircraft' => 'ATR 72-500',
                'baggage' => '15 kg checked + 5 kg hand',
                'seats_available' => 25,
            ],
            [
                'airline' => 'Shree Airlines',
                'flight_number' => 'SHA 902',
                'from_city' => 'Janakpur',
                'to_city' => 'Kathmandu',
                'departure_time' => '19:00:00',
                'arrival_time' => '19:35:00',
                'duration' => '35 min',
                'fare' => 11500,
                'refundable' => true,
                'aircraft' => 'Bombardier CRJ-200',
                'baggage' => '25 kg checked + 7 kg hand',
                'seats_available' => 32,
            ],
        ];

        foreach ($flights as $flight) {
            Flight::create($flight);
        }

        $this->command->info('✓ Added ' . count($flights) . ' return flights');
    }
}